import Foundation
import Observation
import WidgetKit

let defaultExcludedBundleIDs = [
    "com.1password.1password",
    "com.bitwarden.desktop",
    "org.keepassx.keepassxc",
    "com.hicknhacksoftware.MacPass",
    "com.markmcguill.strongbox",
    "com.markmcguill.strongbox.pro",
    "com.lastpass.LastPass",
    "in.sinew.Enpass-Desktop",
    "me.proton.pass.electron",
    "com.keepersecurity.passwordmanager",
    "com.apple.Passwords",
    "com.apple.Passwords.MenuBarExtra",
    "com.apple.keychainaccess",
    "com.microsoft.Excel",
]

@MainActor @Observable
final class AppSettings {
    static let shared: AppSettings = {
        #if DEBUG
        if SettingsSnapshot.output != nil {
            let suite = "dev.gustaf.Rinse.snapshot"
            UserDefaults.standard.removePersistentDomain(forName: suite)
            return AppSettings(store: UserDefaults(suiteName: suite) ?? .standard)
        }
        #endif
        return AppSettings(store: UserDefaults(suiteName: RinseDefaults.suiteName) ?? .standard)
    }()

    @ObservationIgnored private let store: UserDefaults

    var isEnabled: Bool {
        didSet {
            store.set(isEnabled, forKey: RinseDefaults.isEnabledKey)
            ControlCenter.shared.reloadControls(ofKind: RinseDefaults.controlKind)
        }
    }
    var showMenuBarIcon: Bool { didSet { store.set(showMenuBarIcon, forKey: "showMenuBarIcon") } }
    var markAutoGenerated: Bool { didSet { store.set(markAutoGenerated, forKey: "markAutoGenerated") } }
    var excludedBundleIDs: [String] { didSet { store.set(excludedBundleIDs, forKey: "excludedBundleIDs") } }
    var transforms: TransformOptions {
        didSet {
            store.set(transforms.removeInvisibles, forKey: "removeInvisibles")
            store.set(transforms.trimWhitespace, forKey: "trimWhitespace")
            store.set(transforms.straightenQuotes, forKey: "straightenQuotes")
            store.set(transforms.removeTrackingParameters, forKey: "removeTrackingParameters")
            store.set(transforms.stripMailto, forKey: "stripMailto")
            store.set(transforms.stripTel, forKey: "stripTel")
        }
    }

    init(store: UserDefaults) {
        let defaults = TransformOptions()
        store.register(defaults: [
            RinseDefaults.isEnabledKey: true,
            "showMenuBarIcon": true,
            "markAutoGenerated": false,
            "excludedBundleIDs": defaultExcludedBundleIDs,
            "removeInvisibles": defaults.removeInvisibles,
            "trimWhitespace": defaults.trimWhitespace,
            "straightenQuotes": defaults.straightenQuotes,
            "removeTrackingParameters": defaults.removeTrackingParameters,
            "stripMailto": defaults.stripMailto,
            "stripTel": defaults.stripTel,
        ])
        self.store = store
        isEnabled = store.bool(forKey: RinseDefaults.isEnabledKey)
        showMenuBarIcon = store.bool(forKey: "showMenuBarIcon")
        markAutoGenerated = store.bool(forKey: "markAutoGenerated")
        excludedBundleIDs = store.stringArray(forKey: "excludedBundleIDs") ?? defaultExcludedBundleIDs
        transforms = TransformOptions(
            removeInvisibles: store.bool(forKey: "removeInvisibles"),
            trimWhitespace: store.bool(forKey: "trimWhitespace"),
            straightenQuotes: store.bool(forKey: "straightenQuotes"),
            removeTrackingParameters: store.bool(forKey: "removeTrackingParameters"),
            stripMailto: store.bool(forKey: "stripMailto"),
            stripTel: store.bool(forKey: "stripTel")
        )
    }

    func reloadIsEnabled() {
        let stored = store.bool(forKey: RinseDefaults.isEnabledKey)
        if stored != isEnabled { isEnabled = stored }
    }
}
