import AppKit

private let rinseMarkerType = NSPasteboard.PasteboardType("dev.gustaf.Rinse.hasRun")
private let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

private let skippedTypes: Set<NSPasteboard.PasteboardType> = [
    rinseMarkerType,
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .fileURL,
]

private let plainTextTypes: Set<NSPasteboard.PasteboardType> = [
    .string,
    sourceType,
    .init("public.utf16-plain-text"),
    .init("public.utf16-external-plain-text"),
    .init("NSStringPboardType"),
    .init("CorePasteboardFlavorType 0x75743136"),
]

@MainActor
final class ClipboardMonitor {
    private let settings: AppSettings
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int

    init(settings: AppSettings) {
        self.settings = settings
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        Task { await run() }
    }

    private func run() async {
        while !Task.isCancelled {
            poll()
            try? await Task.sleep(for: .milliseconds(150), tolerance: .milliseconds(50))
        }
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        settings.reloadIsEnabled()
        guard settings.isEnabled, !NSEvent.modifierFlags.contains(.option) else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: skippedTypes), let original = pasteboard.string(forType: .string) else { return }
        let source = pasteboard.string(forType: sourceType) ?? NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""
        guard !settings.excludedBundleIDs.contains(source) else { return }

        let cleaned = clean(original, options: settings.transforms)
        guard cleaned != original || !types.isSubset(of: plainTextTypes) else { return }
        pasteboard.clearContents()
        pasteboard.setString(cleaned, forType: .string)
        pasteboard.setData(Data(), forType: rinseMarkerType)
        pasteboard.setString(source, forType: sourceType)
        if settings.markAutoGenerated { pasteboard.setData(Data(), forType: autoGeneratedType) }
        lastChangeCount = pasteboard.changeCount
    }
}
