import SwiftUI

struct AdvancedSettings: View {
    @Bindable var settings: AppSettings

    var body: some View {
        Form {
            Section {
                Toggle("Improve compatibility with apps appending to the clipboard", isOn: $settings.markAutoGenerated)
            } header: {
                Text("When Clearing Formatting")
            } footer: {
                Text("Marks cleaned text as auto-generated so clipboard-merging features (like Alfred's) keep working. Some clipboard managers may then ignore cleaned text.")
            }
        }
        .formStyle(.grouped)
        .frame(height: 180)
    }
}
